### ISSUE TITLE
TypeError on 0.6 update

### ISSUE THREAD

**Issue by pascalduez** [satya164/jest-file-snapshot#31]
Hello,

after updating to version `0.6.0` I get a TypeError when I have diverging snapshots.

```
  TypeError: diff is not a function

    164 |   });
    165 |
  > 166 |   expect(code).toMatchFile();
        |                ^
    167 | });
    168 |

    at Object.toMatchFile (node_modules/jest-file-snapshot/index.js:118:24)
    at __EXTERNAL_MATCHER_TRAP__ (node_modules/expect/build/index.js:325:30)
    at Object.throwingMatcher [as toMatchFile] (node_modules/expect/build/index.js:326:15)
    at toMatchFile (test/index.spec.js:166:16)
```

Env:
Node.js 22
npm 10.7.0
Jest 29.7.0

**Comment by pascalduez** [comment]
https://github.com/satya164/jest-file-snapshot/blob/4b7932fbba11046fce777feae91f805a3fba2bc9/index.js#L5-L7

I can get it working by changing the import to: `const { diff } = require('jest-diff');`

Which match the named export we can see in sources:   
https://github.com/jestjs/jest/blob/4e56991693da7cd4c3730dc3579a1dd1403ee630/packages/jest-diff/src/index.ts#L62

```
npm ls jest-diff

├─┬ jest-file-snapshot@0.6.0
│ └── jest-diff@29.7.0
└─┬ jest@29.7.0
  └─┬ @jest/core@29.7.0
    └─┬ jest-snapshot@29.7.0
      ├── jest-diff@29.7.0 deduped
      └─┬ jest-matcher-utils@29.7.0
        └── jest-diff@29.7.0 deduped
```

**Comment by pascalduez** [comment]
Probably introduced in https://github.com/satya164/jest-file-snapshot/commit/abfef6c092af468e41ca2b2950cae9baba2d4095 where `jest-diff` is bumped from version 26 to 29.
